apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: expense-tracker
type: Opaque
data:
  username: dXNlcg==  # "user" encoded
  password: cGFzcw==  # "pass" encoded
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app: expense-tracker
data:
  host: "expense-tracker-db.xxxxxxxxxxxx.us-east-1.rds.amazonaws.com"
  name: "expenses_db"
  port: "5432"
