# .github/workflows/cd.yml

name: CD Tracker App Backend

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: 'Docker image tag to deploy'
        required: true
      ECR_REPO:
        description: 'ECR repository name'
        required: true
      AWS_REGION:
        description: 'AWS region'
        required: true
      APP_NAME:
        description: 'Name of the application'
        required: true

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (optional if pulling manifests from GitHub)
        uses: actions/checkout@v4

      - name: Print Input Values
        run: |
          echo "Deploying application..."
          echo "APP_NAME: ${{ inputs.APP_NAME }}"
          echo "IMAGE_TAG: ${{ inputs.IMAGE_TAG }}"
          echo "ECR_REPO: ${{ inputs.ECR_REPO }}"
          echo "AWS_REGION: ${{ inputs.AWS_REGION }}"

      # Example: Authenticate to AWS if needed
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      # Example: Pull Image from ECR or Deploy using kubectl/helm
      - name: Deploy to Kubernetes (dummy step)
        run: |
          echo "Deploying ${{ inputs.APP_NAME }} with image ${{ inputs.ECR_REPO }}:${{ inputs.IMAGE_TAG }}"
          # Add your actual deployment logic here
          # e.g. update manifest and apply with kubectl
